<?php

/**
 * @file
 * Contains commerce_recruiting.module.
 */

/**
 * Implements hook_theme().
 */
function commerce_recruiting_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['friend_share_block'] = [
    'path' => $path . '/templates',
    'template'  => 'friend-share-block',
    'variables' => [
      'share_link' => NULL,
      'block_headline' => NULL,
      'block_description' => NULL,
    ],
  ];
  $theme['recruiter_campaigns'] = [
    'path' => $path . '/templates',
    'template'  => 'recruiter-campaigns',
    'variables' => [
      'campaigns' => [],
    ],
  ];
  $theme['recruiting_summary'] = [
    'path' => $path . '/templates',
    'template'  => 'recruiting-summary',
    'variables' => [
      'summary' => NULL,
    ],
  ];
  $theme['recruiting'] = [
    'render element' => 'elements',
    'file' => 'commerce_recruiting.page.inc',
    'template' => 'recruiting',
  ];
  $theme['recruiting_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'commerce_recruiting.page.inc',
  ];
  return $theme;
}
