#!/usr/bin/env bash

## Run phpunit tests
##
## Tests:
## - fin run_tests --filter 'MyTest'

set -e

fin exec composer install
fin drush site-install -y
fin drush en commerce_recruiting -y
fin drush en commerce_checkout commerce_product_bundle devel_entity_updates admin_toolbar twig_tweak -y
