#!/usr/bin/env bash

## Run phpunit tests
##
## Tests:
## - fin run_tests --filter 'MyTest'
##
## Test calls:
## - fin run_tests --filter 'EventSubscriber\\RecruitmentCheckoutSubscriberTest'
## - fin run_tests --filter 'Kernel\\CampaignManagerTest'
## - fin run_tests --filter 'Kernel\\RecruitmentManagerTest'
## - fin run_tests --filter 'Kernel\\RecruitmentSessionTest'
## - fin run_tests --filter 'Unit\\EncryptionTest'

set -e

fin exec /var/www/vendor/bin/phpunit $*
