#!/usr/bin/env bash

## Run phpunit tests
##
## Tests:
## - fin run_tests --filter 'MyTest'
##
## Test calls:
## - fin run_tests --filter 'EventSubscriber\\RecruitingCheckoutSubscriberTest'
## - fin run_tests --filter 'Kernel\\RecruitingManagerTest'
## - fin run_tests --filter 'Unit\\EncryptionTest'

set -e

fin exec /var/www/vendor/bin/phpunit $*
